# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180127_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='手机', max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=3, help_text='性别: 1(男),2(女),3(未知)', verbose_name='性别'),
        ),
    ]
