# Generated by Django 2.0.5 on 2018-06-11 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('content', models.TextField(blank=True, help_text='博客正文', verbose_name='博客正文')),
                ('title', models.TextField(help_text='标题', verbose_name='标题')),
                ('num', models.PositiveIntegerField(blank=True, default=0, help_text='数量', null=True, verbose_name='数量')),
                ('pinned', models.BooleanField(default=False, help_text='置顶', verbose_name='置顶')),
                ('excerpt', models.CharField(blank=True, help_text='摘要', max_length=200, verbose_name='摘要')),
                ('sumary_img', models.ImageField(default='', help_text='图片url', upload_to='static/images/%Y/%m/%d', verbose_name='图片url')),
                ('category', models.ForeignKey(help_text='类别', on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='类别')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
    ]
