# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(help_text='类别名字', verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='Category', related_query_name='Category', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
